Models/EnumStatusTarefa.cs
namespace GerenciadorDeTarefas.Models
{
    public enum EnumStatusTarefa
    {
        Pendente,
        Finalizado
    }
}

Models/ErrorViewModel.cs
namespace GerenciadorDeTarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }

}

Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GerenciadorDeTarefas.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public EnumStatusTarefa Status { get; set; }
    }
}

Controllers/HomeController.cs
using GerenciadorDeTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GerenciadorDeTarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TarefaController.cs
using Microsoft.AspNetCore.Mvc;
using GerenciadorDeTarefas.Models;
using GerenciadorDeTarefas.Context;

namespace GerenciadorDeTarefas.Controllers
{
    public class TarefaController : Controller
    {
        
        private readonly OrganizadorContext _context;

        public TarefaController(OrganizadorContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var tarefas = _context.Tarefas.ToList();
            return View(tarefas);
        }
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Tarefa tarefas)
        {
            if (ModelState.IsValid)
            {
                _context.Tarefas.Add(tarefas);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefas);
        }

        public IActionResult Editar(int id)
        {
            var tarefa = _context.Tarefas.Find(id);
            if (tarefa == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(tarefa);
            }
        }
        [HttpPost]
        public IActionResult Editar(Tarefa tarefas)
        {
            var tarefaDoBanco = _context.Tarefas.Find(tarefas.Id);

            tarefaDoBanco.Titulo = tarefas.Titulo;
            tarefaDoBanco.Descricao = tarefas.Descricao;
            tarefaDoBanco.Data = tarefas.Data;
            tarefaDoBanco.Status = tarefas.Status;

            _context.Tarefas.Update(tarefaDoBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(int id)
        {
            var tarefa = _context.Tarefas.Find(id);
            if (tarefa == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(tarefa);
            }
        }

        public IActionResult Deletar(int id)
        {
            var tarefa = _context.Tarefas.Find(id);
            if (tarefa == null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(tarefa);
            }
        }

        [HttpPost]
        public IActionResult Deletar(Tarefa tarefas)
        {
            var tarefaDoBanco = _context.Tarefas.Find(tarefas.Id);

            _context.Tarefas.Remove(tarefaDoBanco);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Gerenciador de Tarefas</h1>
    <p>Criado por Breno Carneiro. <a href="https://github.com/BrenoCarneiro/">Link para o meu perfil no GitHub</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciador de Tarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GerenciadorDeTarefas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciador de Tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Gerenciador de Tarefas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tarefa/Criar.cshtml
@model GerenciadorDeTarefas.Models.Tarefa


@{
    ViewData["Title"] = "Criar Nova Tarefa";
}

<h3>Criar nova tarefa</h3>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label">Título</label>
                <input asp-for="Titulo" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descrição</label>
                <input asp-for="Descricao" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input type="datetime-local" asp-for="Data" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr />
<div>
    <a asp-action="Index">Voltar</a>
</div>

Views/Tarefa/Deletar.cshtml
@model GerenciadorDeTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Deletar Tarefa";
}

<h3 style="color: red;">Deseja realmente deletar essa tarefa?<br /> (Essa operação é irreversível)</h3>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            Título:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-2">
            Descrição:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-2">
            Data:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Data)
        </dt>
        <dt class="col-sm-2">
            Status:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Status)
        </dt>
    </dl>
</div>

<form asp-action="Deletar">
    <input type="submit" value="Deletar" class="btn btn-danger" />
</form>
<br />
<a asp-action="Index">Voltar</a>

Views/Tarefa/Detalhes.cshtml
@model GerenciadorDeTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Detalhes da Tarefa";
}

<h3>Detalhes da Tarefa</h3>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            Título:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-2">
            Descrição:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-2">
            Data:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Data)
        </dt>
        <dt class="col-sm-2">
            Status:
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Status)
        </dt>
    </dl>
</div>
<a asp-action="Editar" asp-route-id="@Model.Id">Editar</a> |
<a asp-action="Deletar" asp-route-id="@Model.Id">Deletar</a> |
<a asp-action="Index">Voltar</a>

Views/Tarefa/Editar.cshtml
@model GerenciadorDeTarefas.Models.Tarefa


@{
    ViewData["Title"] = "Editar Tarefa";
}

<h1>Editar Tarefa</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label">Título</label>
                <input asp-for="Titulo" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descrição</label>
                <input asp-for="Descricao" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label">Data</label>
                <input type="datetime-local" asp-for="Data" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label">Status</label>
                <select asp-for="Status"
                        class="form-control form-select"
                        asp-items="Html.GetEnumSelectList<EnumStatusTarefa>()">
                </select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr />
<div>
    <a asp-action="Index">Voltar</a>
</div>

Views/Tarefa/Index.cshtml
@model IEnumerable<GerenciadorDeTarefas.Models.Tarefa>


@{
    ViewData["Title"] = "Listagem de Tarefas";
}

<h2>Listagem de Tarefas</h2>

<div class="pt-2 pb-2 d-flex flex-row">
    <a asp-action="Criar" class="btn btn-primary">Nova Tarefa</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
               Título
            </th>
            <th>
                Descrição
            </th>
            <th>
                Data
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Data)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Status)
                </td>
                <td>
                    <a asp-action="Editar" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Deletar" asp-route-id="@item.Id">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>